# Generated by Django 3.2 on 2022-11-29 10:20

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_division', models.CharField(blank=True, max_length=255, null=True)),
                ('positionname', models.CharField(blank=True, max_length=50, null=True)),
                ('desired_keywords', models.CharField(blank=True, max_length=50, null=True)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('est_completion_date', models.DateField(blank=True, null=True)),
                ('assigneeid', models.IntegerField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('assigner', models.CharField(blank=True, max_length=128, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('statusid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_assignment',
            },
        ),
        migrations.CreateModel(
            name='CandidatePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'priority',
                'db_table': 'main_priority',
            },
        ),
        migrations.CreateModel(
            name='CandidateResumeTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'templates',
                'db_table': 'main_templates',
            },
        ),
        migrations.CreateModel(
            name='CandidateSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'SkillLevel',
                'db_table': 'main_skill_level',
            },
        ),
        migrations.CreateModel(
            name='CandidateStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'status',
                'db_table': 'main_status',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'main_company',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'main_keyword',
            },
        ),
        migrations.CreateModel(
            name='PlatformOrReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'PlatformOrReferral',
                'db_table': 'main_platform_or_referral',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'main_position',
            },
        ),
        migrations.CreateModel(
            name='PowerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('query', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'main_power_search',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'main_project',
            },
        ),
        migrations.CreateModel(
            name='CandidateTable',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('candidateFileNameOriginal', models.FileField(blank=True, null=True, upload_to='files/')),
                ('template', tinymce.models.HTMLField(blank=True, null=True)),
                ('fileUploadDate', models.DateField(blank=True, null=True)),
                ('archive', models.BooleanField(default=True)),
                ('date_added', models.DateField(auto_now_add=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('ww', models.IntegerField(blank=True, null=True)),
                ('adder', models.IntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('history', models.CharField(blank=True, max_length=500, null=True)),
                ('positionOrPerson', models.CharField(blank=True, max_length=255, null=True)),
                ('refferedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('specialitySkillSet', models.CharField(blank=True, max_length=255, null=True)),
                ('semi', models.CharField(blank=True, max_length=255, null=True)),
                ('intel', models.CharField(blank=True, max_length=255, null=True)),
                ('project1', models.CharField(blank=True, max_length=255, null=True)),
                ('project2', models.CharField(blank=True, max_length=255, null=True)),
                ('project3', models.CharField(blank=True, max_length=255, null=True)),
                ('fileUploadUser', models.CharField(blank=True, max_length=255, null=True)),
                ('candidateFileName', models.CharField(blank=True, max_length=255, null=True)),
                ('candidateFileNamePDF', models.CharField(blank=True, max_length=255, null=True)),
                ('candidateFileNameOriginalFull', models.CharField(blank=True, max_length=255, null=True)),
                ('activity', models.TextField(blank=True, null=True)),
                ('pay', models.TextField(blank=True, null=True)),
                ('skill_keywords', models.TextField(blank=True, null=True)),
                ('skill_keywords_full', models.TextField(blank=True, null=True)),
                ('candidateFileContents', models.TextField(blank=True, null=True)),
                ('active_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.assignment')),
                ('fk_ra_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('fk_ra_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.position')),
                ('fk_ra_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
                ('plateformOrReferral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.platformorreferral')),
                ('priority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.candidatepriority')),
                ('skillLevel', models.ManyToManyField(blank=True, null=True, to='core.CandidateSkillLevel')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.candidatestatus')),
            ],
            options={
                'verbose_name_plural': 'candidates',
                'db_table': 'main_candidate_tbl',
            },
        ),
    ]
