# Generated by Django 3.2 on 2022-10-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_division', models.CharField(blank=True, max_length=255, null=True)),
                ('positionname', models.CharField(blank=True, max_length=50, null=True)),
                ('desired_keywords', models.CharField(blank=True, max_length=50, null=True)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('est_completion_date', models.DateField(blank=True, null=True)),
                ('assigneeid', models.IntegerField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('assigner', models.CharField(blank=True, max_length=128, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('statusid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assignment',
                'managed': False,
            },
        ),
    ]
