# Generated by Django 3.2 on 2022-10-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='active_assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.assignment'),
            preserve_default=False,
        ),
    ]
