# Generated by Django 3.2 on 2022-12-07 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateskilllevel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='skillLevel',
            field=models.ManyToManyField(blank=True, null=True, related_name='skillLevel', to='core.CandidateSkillLevel'),
        ),
    ]
