# Generated by Django 3.2 on 2022-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateTable',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('history', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('active_assignment', models.CharField(blank=True, max_length=50, null=True)),
                ('adder', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('fk_ra_company', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_ra_project', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_ra_position', models.CharField(blank=True, max_length=255, null=True)),
                ('skill_keywords', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('candidateFileName', models.CharField(blank=True, max_length=255, null=True)),
                ('candidateFileContents', models.TextField(blank=True, null=True)),
                ('candidateFileNameOriginal', models.CharField(blank=True, max_length=255, null=True)),
                ('candidateFileNamePDF', models.CharField(blank=True, max_length=255, null=True)),
                ('fileUploadDate', models.DateTimeField(blank=True, null=True)),
                ('candidateFileNameOriginalFull', models.CharField(blank=True, max_length=255, null=True)),
                ('fileUploadUser', models.CharField(blank=True, max_length=255, null=True)),
                ('archive', models.IntegerField(blank=True, null=True)),
                ('skill_keywords_full', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'candidates',
                'db_table': 'candidate_tbl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HelpText',
            fields=[
                ('Help_Text', models.TextField(blank=True, max_length=255, null=True)),
                ('Help_Text_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Help_ID_Name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'help_text',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('keyword_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'keyword',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('objectType', models.CharField(blank=True, max_length=40, null=True)),
                ('dateStamp', models.DateTimeField()),
                ('componentGUID', models.CharField(blank=True, max_length=40, null=True)),
                ('userId', models.CharField(blank=True, max_length=40, null=True)),
                ('data', models.TextField()),
                ('securityGroups', models.TextField()),
            ],
            options={
                'db_table': 'repository',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=50, null=True)),
                ('status_description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym', models.CharField(blank=True, max_length=128, null=True)),
                ('keywordid', models.IntegerField()),
            ],
            options={
                'db_table': 'synonym',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
