# Generated by Django 3.2 on 2022-10-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
