# Generated by Django 3.2 on 2022-10-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_candidatetable_active_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='fk_ra_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company'),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='fk_ra_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.position'),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='fk_ra_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
