# Generated by Django 3.2 on 2022-10-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_candidatetable_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='fileUploadDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
