# Generated by Django 3.2 on 2022-10-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20221007_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='candidateFileNameOriginal',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
