# Generated by Django 3.2 on 2022-10-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221007_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='candidateFileNamePDF',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
