# Generated by Django 3.2 on 2022-10-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_candidatetable_candidatefilenamepdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='candidateFileNamePDF',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
