# Generated by Django 3.2 on 2022-10-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221031_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatetable',
            old_name='sourcePositionOrPerson',
            new_name='positionOrPerson',
        ),
    ]
