# Generated by Django 3.2 on 2022-11-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_candidatetable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetable',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.candidatestatus'),
        ),
    ]
