# Generated by Django 3.2 on 2022-11-02 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20221102_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatetable',
            name='priority',
        ),
    ]
