# Generated by Django 3.2 on 2022-11-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_candidatetable_candidatefilecontents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformOrReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Platform/Referral',
            },
        ),
        migrations.RemoveField(
            model_name='candidatetable',
            name='plateformOrReferral',
        ),
    ]
