# Generated by Django 3.2 on 2022-11-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_candidatetable_archive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatetable',
            old_name='customeTemplate',
            new_name='template',
        ),
    ]
