# Generated by Django 3.2 on 2022-10-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_division', models.CharField(blank=True, max_length=255, null=True)),
                ('positionname', models.CharField(blank=True, max_length=50, null=True)),
                ('desired_keywords', models.CharField(blank=True, max_length=50, null=True)),
                ('target_start_date', models.DateField(blank=True, null=True)),
                ('est_completion_date', models.DateField(blank=True, null=True)),
                ('assigneeid', models.IntegerField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('assigner', models.CharField(blank=True, max_length=128, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=255, null=True)),
                ('statusid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assignment',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='CandidateTable',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('history', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('adder', models.IntegerField(blank=True, null=True)),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('skill_keywords', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('candidateFileName', models.CharField(blank=True, max_length=255, null=True)),
                ('candidateFileContents', models.TextField(blank=True, null=True)),
                ('candidateFileNameOriginal', models.FileField(blank=True, null=True, upload_to='files/')),
                ('candidateFileNamePDF', models.CharField(blank=True, max_length=255, null=True)),
                ('fileUploadDate', models.DateTimeField(blank=True, null=True)),
                ('candidateFileNameOriginalFull', models.CharField(blank=True, max_length=255, null=True)),
                ('fileUploadUser', models.CharField(blank=True, max_length=255, null=True)),
                ('archive', models.IntegerField(blank=True, null=True)),
                ('skill_keywords_full', models.TextField(blank=True, null=True)),
                ('active_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.assignment')),
                ('fk_ra_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.company')),
                ('fk_ra_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.position')),
                ('fk_ra_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project')),
            ],
            options={
                'verbose_name_plural': 'candidates',
                'db_table': 'candidate_tbl',
            },
        ),
    ]
