# Generated by Django 3.2 on 2022-10-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221012_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
