# Generated by Django 3.2 on 2022-10-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_candidatetable_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('query', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
