# Generated by Django 3.2 on 2022-10-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_candidatetable_active_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetable',
            name='activity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='intel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='pay',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='plateformOrReferral',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='priority',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='project1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='project2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='project3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='refferedBy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='semi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='skillLevel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='sourcePositionOrPerson',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='specialitySkillSet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
