# Generated by Django 3.2 on 2022-10-31 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20221031_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetable',
            name='ww',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
