# Generated by Django 3.2 on 2022-11-02 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
