# Generated by Django 3.2 on 2022-11-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_candidatetable_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatetable',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='candidatetable',
            name='skillLevel',
        ),
    ]
