# Generated by Django 3.2 on 2022-11-02 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20221102_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'priority',
            },
        ),
        migrations.CreateModel(
            name='CandidateSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Skill Level',
            },
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.candidatepriority'),
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='skillLevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.candidateskilllevel'),
        ),
    ]
