# Generated by Django 3.2 on 2022-11-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_candidatetable_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatetable',
            name='skillLevel',
        ),
        migrations.AddField(
            model_name='candidatetable',
            name='skillLevel',
            field=models.ManyToManyField(blank=True, null=True, to='core.CandidateSkillLevel'),
        ),
    ]
