# Generated by Django 3.2 on 2022-11-08 11:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20221102_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='candidateFileContents',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
