# Generated by Django 3.2 on 2022-11-09 05:23

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_candidatetable_plateformorreferral'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateResumeTemplates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'templates',
            },
        ),
        migrations.AlterField(
            model_name='candidatetable',
            name='candidateFileContents',
            field=models.TextField(blank=True, null=True),
        ),
    ]
