# Generated by Django 3.2 on 2022-11-09 11:26

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20221109_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetable',
            name='customeTemplate',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
