# Generated by Django 3.2 on 2022-11-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_candidatetable_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatetable',
            name='archive',
            field=models.BooleanField(default=True),
        ),
    ]
