# Generated by Django 3.2 on 2022-11-29 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_custometemplate_candidatetable_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateskilllevel',
            options={'verbose_name_plural': 'SkillLevel'},
        ),
        migrations.AlterModelOptions(
            name='platformorreferral',
            options={'verbose_name_plural': 'PlatformOrReferral'},
        ),
    ]
